# Generated by Django 3.1 on 2020-08-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200821_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidor',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.persona'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
