# Generated by Django 3.1 on 2020-08-22 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200821_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha_registro')),
                ('fecha_log', models.DateTimeField(auto_now_add=True, verbose_name='ultimo_ingreso')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('persona', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
