export const OBTENER_ANUNCIOS = "OBTENER_ANUNCIOS"
export const OBTENER_ANUNCIO_ACTUAL = "OBTENER_ANUNCIO_ACTUAL"
export const AGREGAR_ANUNCIO = "AGREGAR_ANUNCIO";
export const EDITAR_ANUNCIO = "EDITAR_ANUNCIO";
export const ELIMINAR_ANUNCIO = "ELIMINAR_ANUNCIO";
export const OBTENER_ANUNCIOS_USUARIO = "OBTENER_ANUNCIOS_USUARIO";

export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
export const OBTENER_USUARIO = "OBTENER_USUARIO";