# Generated by Django 3.1 on 2020-08-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='No disponible', max_length=50)),
                ('descripcion', models.CharField(blank=True, default='No disponible', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='No disponible', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='No disponible', max_length=50)),
                ('descripcion', models.CharField(blank=True, default='Dato no ingresado', max_length=50)),
                ('banner', models.CharField(blank=True, default='No posee banner', max_length=300)),
                ('estado', models.BooleanField(default=1)),
                ('fecha_inicio', models.DateField(auto_now_add=True, null=True)),
                ('fecha_termino', models.DateField(auto_now=True, null=True)),
                ('vacantes', models.IntegerField(default=0)),
                ('cant_interesados', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knoot.categoria')),
                ('habilidades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knoot.habilidad')),
            ],
        ),
    ]
