# Generated by Django 3.1 on 2020-08-18 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knoot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='habilidades',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='fecha_termino',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='rel_habilidad_anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anuncio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knoot.anuncio')),
                ('habilidad', models.ManyToManyField(to='knoot.Habilidad')),
            ],
        ),
    ]
