# Generated by Django 3.1 on 2020-08-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knoot', '0002_auto_20200818_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='habilidad',
            field=models.ManyToManyField(to='knoot.Habilidad'),
        ),
        migrations.DeleteModel(
            name='rel_habilidad_anuncio',
        ),
    ]
