# Generated by Django 3.1 on 2020-08-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knoot', '0003_auto_20200818_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='habilidad',
            new_name='habilidades',
        ),
    ]
