# Generated by Django 3.1 on 2020-08-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knoot', '0004_auto_20200818_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='habilidades',
            new_name='habilidad',
        ),
    ]
