# Generated by Django 3.1 on 2020-08-19 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knoot', '0005_auto_20200818_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Sin Especificar', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Sin Especificar', max_length=50)),
                ('apellido', models.CharField(blank=True, default='Sin Especificar', max_length=50)),
                ('email', models.CharField(blank=True, default='Sin Especificar', max_length=100)),
                ('telefono', models.CharField(blank=True, default='0999999999', max_length=13)),
                ('fecha_nacimiento', models.DateField(auto_now_add=True, null=True)),
                ('lugar_origen', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='knoot.persona')),
                ('rol', models.CharField(blank=True, default='Sin Especificar', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, default='Invalido', max_length=250)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='knoot.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='Sin Especificar', max_length=50)),
                ('descripcion', models.CharField(blank=True, default='Sin Especificar', max_length=300)),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='knoot.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='knoot.persona')),
                ('descripcion', models.CharField(blank=True, default='Sin Especificar', max_length=150)),
                ('foto', models.CharField(blank=True, default='Sin Especificar', max_length=150)),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knoot.facultad')),
                ('habilidad', models.ManyToManyField(to='knoot.Habilidad')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='consumidor',
            field=models.ManyToManyField(to='knoot.Consumidor'),
        ),
    ]
