# Generated by Django 3.1 on 2020-08-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knoot', '0006_auto_20200818_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='consumidor',
            new_name='interesados',
        ),
    ]
