# Generated by Django 3.1 on 2020-08-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knoot', '0007_auto_20200818_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='nombre',
            field=models.CharField(blank=True, choices=[('FIEC', 'Facultad de Ingenieria en Electricidad y Computacion'), ('FCNM', 'Facultad de Ciencias Naturales y Matematicas'), ('EDCOM', 'Escuela de Diseno y Comunicacion '), ('FICT', 'Facultad de Ingenieria en Ciencias de la Tierra'), ('FIMCP', 'Facultad de Ingenieria en Mecanica y Ciencias de la Produccion')], default='Sin Especificar', max_length=150),
        ),
    ]
