# Generated by Django 3.1 on 2020-08-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knoot', '0008_auto_20200818_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='interesados',
            field=models.ManyToManyField(blank=True, null=True, to='knoot.Consumidor'),
        ),
    ]
