# Generated by Django 3.1 on 2020-08-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knoot', '0009_auto_20200818_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='descripcion',
            field=models.CharField(blank=True, default='Dato no ingresado', max_length=300),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, default='Sin Especificar', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
