# Generated by Django 3.1 on 2020-08-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knoot', '0010_auto_20200818_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='interesados',
            field=models.ManyToManyField(blank=True, to='knoot.Consumidor'),
        ),
    ]
