# Generated by Django 3.1 on 2020-08-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knoot', '0011_auto_20200819_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='rol',
            field=models.CharField(blank=True, choices=[('LECTOR', 'Lector'), ('ESCRITOR', 'Escritor'), ('PROPIETARIO', 'Propietario ')], default='Sin Especificar', max_length=30),
        ),
    ]
